# Generated by Django 3.0.2 on 2022-02-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fiction', 'fiction'), ('technology', 'technology'), ('science', 'science'), ('other', 'other')], max_length=20)),
                ('publisher', models.CharField(max_length=255)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('days_to_borrow', models.PositiveIntegerField(default=0)),
                ('borrowed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
