# Generated by Django 3.0.2 on 2022-02-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220206_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
