# Generated by Django 3.0.2 on 2022-02-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_available_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
